app:
  name: default

#### To enable SQL logging at Hibernate-level by providing the following logger options ###
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

#location of the discovery server
eureka:
  instance:
    preferIpAddress: true
  client:
    service:
      url:
        defaultZone: http://localhost:8761/eureka/
#security related configuration
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-52510621.okta.com/oauth2/default

okta:
  oauth2:
    issuer: https://dev-52510621.okta.com/oauth2/default
