app:
  name: default

#### To enable SQL logging at Hibernate-level by providing the following logger options ###
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

#location of the discovery server
eureka:
  instance:
    preferIpAddress: true
  client:
    service:
      url:
        defaultZone: http://eureka-server:8761/eureka/
