app:
  name: default

#### To enable SQL logging at Hibernate-level by providing the following logger options ###
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

#location of the discovery server
eureka:
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}

spring:
  config:
    import: ${SPRING_CONFIG_IMPORT}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-52510621.okta.com/oauth2/default

okta:
  oauth2:
    issuer: https://dev-52510621.okta.com/oauth2/default
