app:
  name: 'Customer Service Default Configuration'

############# MySQL configuration ##############

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://mysqldb/customerdb
    username: root
    #password: '{cipher}93386b1c11e97618e6b35273257989fc7afe0504c49427631750f6ce90d04c44'
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ##drop n create table again, good for testing, comment this in production; Possible values ..none, validate, update, create-drop; For embedded database create-drop is the default, for others none
      ddl-auto: 'update'
      naming-strategy: 'org.hibernate.cfg.DefaultComponentSafeNamingStrategy'
    defer-datasource-initialization : true #Whether to defer DataSource initialization until after any EntityManagerFactory beans have been created and initialized.
#location of the discovery server
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

endpoints.shutdown.enabled: true
management.endpoint.shutdown.enabled: true
