app:
  name: 'Customer Service Default Configuration'
  
#location of the discovery server
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'


#### To enable SQL logging at Hibernate-level by providing the following logger options ###
logging:
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql: trace


############# MySQL configuration ##############

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/customerdb'
    username: root
    #password: '{cipher}93386b1c11e97618e6b35273257989fc7afe0504c49427631750f6ce90d04c44'
    password: root
    driver-class-name: org.mysql.Driver
  jpa:
    hibernate:
      ##drop n create table again, good for testing, comment this in production; Possible values ..none, validate, update, create-drop; For embedded database create-drop is the default, for others none
      ddl-auto: 'update'
      naming-strategy: 'org.hibernate.cfg.DefaultComponentSafeNamingStrategy'
    defer-datasource-initialization : true #Whether to defer DataSource initialization until after any EntityManagerFactory beans have been created and initialized.
